let selectedProject = '';

function askForPropertyType(projectName) {
    selectedProject = projectName;  // تخزين اسم المشروع الذي اختاره العميل
    const modal = document.getElementById('propertyModal');
    if (modal) {
        modal.style.display = 'block'; // إظهار النافذة
    } else {
        console.log("Modal not found"); // إذا لم يتم العثور على العنصر
    }
}


function closeModal() {
    document.getElementById('propertyModal').style.display = 'none'; // إغلاق النافذة المنبثقة
}

function sendWhatsappWithType(propertyType) {
    const phoneNumber = '201044096035'; // رقم الهاتف الذي ستُرسل إليه الرسالة
    const message = `مرحباً، أريد معرفة المزيد عن ${selectedProject}. نوع العقار: ${propertyType}.\nمن فضلك، تواصل معي.`;
    
    const url = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank'); // فتح رابط واتساب مع الرسالة المحددة
    closeModal(); // إغلاق النافذة بعد إرسال الرسالة
}

function toggleDescription(button) {
    const projectElement = button.parentElement; // الحصول على العنصر الذي يحتوي على المشروع
    const description = projectElement.querySelector('.project-description'); // الحصول على الوصف
    
    // التبديل بين إظهار أو إخفاء الوصف
    description.classList.toggle('active');
}
function sendWhatsApp(choice) {
    const phoneNumber = '201044096035'; // رقم الهاتف المستلم على واتساب
    const message = `بسال عن: ${choice}`; // الرسالة التي تحتوي على الاختيار
    const url = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`; // الرابط مع النص

    // فتح رابط WhatsApp
    window.open(url, '_blank');
}


function showSlide(index) {
    slides.forEach((slide, i) => {
        slide.style.display = i === index ? 'block' : 'none';
    });
}

/**********************/

// تخزين الترجمات في كائن JavaScript
const translations = {
    "ar": {
        "projects": "المشاريع",
        "about": "عن الشركة",
        "marketingTeam": "فريق التسويق",
        "contact": "تواصل معنا",
        "arabic": "العربية",
        "english": "الإنجليزية",
        "german": "الألمانية",
        "russian": "الروسية",
        "french": "الفرنسية",
        "spanish": "الإسبانية",
        
        "mortgage": "تمويل عقاري",
        "shops": "محلات تجارية",
        "installments": "وحدات بالتقسيط",
        "companyPresentation": "مجموعة المهندس الانشائي شنودة بشير تقدم",
        "projectTitle": "مشروع الانتر استار",
        "projectLocation": "الموقع: خلف مستشفي الحياة - الانتركونتننتل - الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "projectDescription": "متبقي 3 استوديوهات\n\n✨الاستوديو مساحته 47 متر ،يحتوي على غرفة وصالة و بلكونة علي حمام السباحة.\n\n✨الموقع مميز قريب من كل الخدمات:\n1-مستشفى الحياة\n2-بالقرب من شاطئ 9\n3-السفارة الروسية\n\n✨طرق الدفع:\nمقدم 50% و الباقي تقسيط على سنة\nوديعة صيانة 10% عند الاستلام مدي الحياة",
        "compoundMarminaAlt": "كمبوند مارمينا",
        "compoundMarminaTitle": "كمبوند مارمينا",
        "compoundMarminaLocation": "الموقع: بجوار كنيسة مارمينا - خلف مدرية التربية والتعليم - الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "compoundMarminaDescription": "🏤كمبوند مارمينا بالغردقة\nشقق واستوديوهات سكنية بالتقسيط 🏡\n\n🔸 المساحات الشقق المتوفرة:\n📐 85م² - 95م² - 100م² - 105م² - 115م²\n\n🔸 المساحات الستوديوهات المتوفرة:\n📐 55م² - 60م² - 65م² - 70م²\n\n🛋️ تقسيم داخلي مميز: 1 أو 2 أو 3 غرف وصالة، يناسب جميع الاحتياجات 👨‍👩‍👧‍👦\n\n🔸 مميزات الكمبوند:\n✨ جميع الشقق تحتوي على بلكونة بإطلالة على حمام السباحة 🌊\n✨ عدد 2 أسانسير لتسهيل التنقل 🛗\n✨ حمام سباحة 🏊‍♂️\n✨ أمن وحراسة 24 ساعة لضمان الأمان 🛡️\n✨ كاميرات مراقبة موزعة في جميع أنحاء الكمبوند 🎥\n\n🔸 الأسعار:\n💰 سعر المتر على الطوب:\nكاش: 12,000 جنيه 💵\nتقسيط: 12,500 جنيه 💳\n\n💡 نظام التقسيط:\nدفع 50% مقدم والباقي على سنة ونصف 📆",
        "kingTutAlt": "مشروع كنج توت",
        "kingTutTitle": "عمارة كنج توت",
        "kingTutLocation": "الموقع: تقسم الوفاء - بجوار فندق كنج توت - الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "kingTutDescription": "✨متبقي عدد 3 محل تجاري\n✨مساحات: 20م - 25م - 58م\n✨مسجل عقد اخضر\n✨يوجد تسهيلات في الدفع و استلام فوري",
        "hegazAlt": "عمارة الحجاز",
        "hegazTitle": "عمارة الحجاز",
        "hegazLocation": "الموقع: امام شركة المهندس لقطع غيار السيارات - طريق الحجاز - الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "hegazDescription": "🏛️شقق للبيع بالحجاز 🏢\n📍 قريب من عمارات المحافظة وسوق الغردقة الجديد\n📍 أمام شركة المهندس لقطع غيار السيارات بالحجاز\n🔑 مميزات العقار:\n🔹 العقار مسجل عقد أخضر، ويوفر لك حصة في الأرض 🌍\n🔹 العمارة جديدة وتحتوي على أسانسير 🛗\n📏 مساحات الشقق المتاحة:\n110 - 115 - 120 - 125 متر مربع 🛏️📐\n✨ تقسيم مثالي للعائلات: 3 غرف نوم 👨‍👩‍👧‍👦\n💰 الأسعار:\nسعر المتر على الطوب: 13,000 جنيه كاش 💵\nسعر المتر على الطوب: 13,500 جنيه تقسيط 💳\n💡 نظام التقسيط: دفع 50% مقدم والباقي تسهيلات في الدفع على 6 شهور 📆"
        ,"portBuildingAlt": "عمارة الميناء",
        "portBuildingTitle": "عمارة الميناء",
        "portBuildingLocation": "الموقع: بالقرب من مارينا الغردقة السياحي- الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "portBuildingDescription": "🏛️مشروع الميناء بقلب مدينة الغردقة.\n🌟بالقرب من المارينا السياحي و بالقرب من جميع الخدمات\n🌟 الوحدات السكنية المتبقية للبيع:\n🔸 شقة 120م (ثلاث غرف)\n🔸 استوديو 55م (غرفة فندقية)\n🔸 استوديو 55م (غرفة نوم)\n💵تسهيلات في السداد وخصم عالكاش"
        ,"jewelBuildingAlt": "الجوهرة",
        "jewelBuildingTitle": "عمارة الجوهرة",
        "jewelBuildingLocation": "الموقع: الاحياء الرئيسي- بجوار كنيسة الام دولاجي - الغردقة",
        "projectDescriptionButton": "الوصف",
        "sendButton": "إرسال",
        "jewelBuildingDescription": "متبقي محل تجارى بمساحة 80م على الطوب"
        ,"projectDescriptionButton": "الوصف",
        "embassyBuildingAlt": "السفارة",
        "embassyBuildingTitle": "عمارة الهضبة",
        "embassyBuildingLocation": "الموقع : الهضبة - بجوار السفارة الالمانية - الغردقة",
        "embassyBuildingDescription": "تم بيع جميع الوحدات",
        "maktabBuildingAlt": "السفارة",
        "maktabBuildingTitle": "عمارة الهضبة",
        "maktabBuildingLocation": "الموقع : شارع مترو الشيراتون - الغردقة",
        "maktabBuildingDescription": "تم بيع جميع الوحدات",
        "ahiaBuildingAlt": "السفارة",
        "ahiaBuildingTitle": "عمارة الجوهرة",
        "ahiaBuildingLocation": "الموقع: الاحياء الرئيسي- بالغردقة",
        "ahiaBuildingDescription": "تم بيع جميع الوحدات",
        "wafaBuildingAlt": "السفارة",
        "wafaBuildingTitle": "عمارة الوفاء",
        "wafaBuildingLocation": "الموقع : بجوار سور الاذاعة - الغردقة",
        "wafaBuildingDescription": "تم بيع جميع الوحدات",
        "propertyModalTitle": "ماذا تسال عن؟",
        "closeButton": "×",
        "apartmentOption": "شقة",
        "studioOption": "استوديو",
        "shopOption": "محل تجارى",
        "marketingTitle": "التواصل مع فريق التسويق",
        "kerollosName": "م. كيرلس نصحي",
        "kerollosRole": "مدير التسويق",
        "kirstenName": "كرستين عاطف",
        "kirstenRole": "تسويق",
        "elinName": "الين ناجح",
        "elinRole": "تسويق",
        "facebookLink": "فيسبوك",
        "whatsappLink": "واتساب",
        "contactTitle": "تواصل معنا",
        "nameLabel": "الاسم:",
        "phoneLabel": "رقم الهاتف:",
        "projectLabel": "المشروع:",
        "hegazOption": "كمبوند مارمينا",
        "interOption": "مشروع الانتر",
        "marinaOption": "مشروع المارينا",
        "hegazOption": "مشروع الحجاز",
        "kingTutOption": "مشروع كنج توت",
        "messageLabel": "الرسالة:",
        "submitButton": "إرسال",
        "aboutTitle": "الشركة",
        "aboutContent": "مجموعة المهندس الإنشائي شنودة بشير العقارية هي شركة رائدة في مجال المقاولات والاستثمار العقاري في منطقة البحر الأحمر. تأسست الشركة بهدف تقديم حلول سكنية وتجارية مبتكرة ومتكاملة تلبي احتياجات عملائنا الكرام. نحن ملتزمون بتقديم أعلى مستويات الجودة في جميع مشاريعنا، مع التركيز على التصميم الفريد، التشطيبات الراقية، واستخدام أحدث التقنيات في البناء",
        "missionTitle": "رسالة الشركة",
        "missionContent": "نحن نسعى لتحقيق رضا عملائنا من خلال تقديم مشاريع عقارية عالية الجودة تسهم في تحسين جودة الحياة وتعزيز الاستثمارات الناجحة.",
        "ownerTitle": "عن صاحب الشركة",
        "ownerName": "المهندس شنودة بشير",
        "ownerContent": "يعتبر المهندس الإنشائي شنودة بشير من الشخصيات البارزة في مجال الإنشاءات والعقارات في منطقة البحر الأحمر. بخبرته الواسعة التي تمتد لسنوات عديدة في هذا المجال، يلتزم بتقديم مشاريع عقارية متميزة تواكب أعلى المعايير العالمية.",
        "contactDetailsTitle": "لمزيد من التفاصيل أو للاستفسار، يمكنكم التواصل معنا عبر:",
        "footerText": "© 2024 مجموعة المهندس الإنشائي شنودة بشير. جميع الحقوق محفوظة."

    },
    "en": {
        // الترجمات الخاصة بالمشاريع والأقسام
        "projects": "Projects",
        "about": "About Us",
        "marketingTeam": "Marketing Team",
        "contact": "Contact Us",
        "arabic": "Arabic",
        "english": "English",
        "german": "German",
        "russian": "Russian",
        "french": "French",
        "spanish": "Spanish",
        
        // الترجمات الخاصة بالأزرار
        "mortgage": "Mortgage",
        "shops": "Shops",
        "installments": "Installments",
        "companyPresentation": "Engineer Shenouda Basheer Group",
        "projectTitle": "Inter Star Project",
        "projectLocation": "Location: Behind Al Hayat Hospital - Intercontinental - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "projectDescription": "3 Studios available\n\n✨The studio is 47 sqm, with one room, a living area, and a balcony overlooking the swimming pool.\n\n✨The location is close to all services:\n1- Al Hayat Hospital\n2- Near Beach 9\n3- The Russian Embassy\n\n✨Payment Methods:\n50% down payment, the rest in installments over 1 year\n10% maintenance deposit upon delivery, valid for life",
        "compoundMarminaAlt": "Compound Marmina",
        "compoundMarminaTitle": "Compound Marmina",
        "compoundMarminaLocation": "Location: Next to Marmina Church - Behind the Directorate of Education - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "compoundMarminaDescription": "🏤Compound Marmina in Hurghada\nApartments and studios available with installments 🏡\n\n🔸 Apartment sizes:\n📐 85m² - 95m² - 100m² - 105m² - 115m²\n\n🔸 Studio sizes:\n📐 55m² - 60m² - 65m² - 70m²\n\n🛋️ Smart interior layout: 1, 2, or 3 rooms with a living area, suitable for all needs 👨‍👩‍👧‍👦\n\n🔸 Compound features:\n✨ All apartments have balconies overlooking the swimming pool 🌊\n✨ Two elevators for easy movement 🛗\n✨ Swimming pool 🏊‍♂️\n✨ 24/7 security and guarding 🛡️\n✨ Surveillance cameras distributed across the compound 🎥\n\n🔸 Prices:\n💰 Price per square meter:\nCash: 12,000 EGP 💵\nInstallments: 12,500 EGP 💳\n\n💡 Installment plan:\n50% down payment, the rest over a year and a half 📆",
        "kingTutAlt": "King Tut Project",
        "kingTutTitle": "King Tut Building",
        "kingTutLocation": "Location: Tawfiq District - Next to King Tut Hotel - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "kingTutDescription": "✨3 commercial shops remaining\n✨Sizes: 20m - 25m - 58m\n✨Registered green contract\n✨Flexible payment options and immediate delivery",
        "hegazAlt": "Al-Hegaz Building",
        "hegazTitle": "Al-Hegaz Building",
        "hegazLocation": "Location: In front of Al-Mohandes Spare Parts Company - Al-Hegaz Road - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "hegazDescription": "🏛️Apartments for sale in Al-Hegaz 🏢\n📍 Near the Governorate Buildings and Hurghada New Market\n📍 In front of Al-Mohandes Spare Parts Company on Al-Hegaz Road\n🔑 Property features:\n🔹 The property is registered with a green contract and includes a share of the land 🌍\n🔹 The building is new and includes an elevator 🛗\n📏 Available apartment sizes:\n110 - 115 - 120 - 125 square meters 🛏️📐\n✨ Perfect layout for families: 3 bedrooms 👨‍👩‍👧‍👦\n💰 Prices:\nPrice per square meter (shell): 13,000 EGP cash 💵\nPrice per square meter (shell): 13,500 EGP installments 💳\n💡 Installment plan: 50% down payment, and the rest in flexible payments over 6 months 📆"
        ,"portBuildingAlt": "Port Building",
        "portBuildingTitle": "Port Building",
        "portBuildingLocation": "Location: Near Hurghada Marina Tourist Area - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "portBuildingDescription": "🏛️Port project in the heart of Hurghada.\n🌟Close to the tourist marina and all services\n🌟 Residential units available for sale:\n🔸 Apartment 120m (three rooms)\n🔸 Studio 55m (hotel room)\n🔸 Studio 55m (bedroom)\n💵Flexible payment options and cash discounts"
        ,"jewelBuildingAlt": "The Jewel",
        "jewelBuildingTitle": "Jewel Building",
        "jewelBuildingLocation": "Location: Main District - Next to Mother Dolagy Church - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Send",
        "jewelBuildingDescription": "A commercial shop of 80m² is available (shell condition)"
        ,"projectDescriptionButton": "Description",
        "embassyBuildingAlt": "Embassy",
        "embassyBuildingTitle": "Al-Hodaba Building",
        "embassyBuildingLocation": "Location: Al-Hodaba - Next to the German Embassy - Hurghada",
        "embassyBuildingDescription": "All units are sold",
        "maktabBuildingAlt": "Embassy",
        "maktabBuildingTitle": "Al-Hodaba Building",
        "maktabBuildingLocation": "Location: Metro Street, Sheraton - Hurghada",
        "maktabBuildingDescription": "All units are sold",
        "ahiaBuildingAlt": "Embassy",
        "ahiaBuildingTitle": "Jewel Building",
        "ahiaBuildingLocation": "Location: Main District - Hurghada",
        "ahiaBuildingDescription": "All units are sold",
        "wafaBuildingAlt": "Embassy",
        "wafaBuildingTitle": "Al-Wafa Building",
        "wafaBuildingLocation": "Location: Next to Radio Fence - Hurghada",
        "wafaBuildingDescription": "All units are sold",
        "propertyModalTitle": "What are you asking about?",
        "closeButton": "×",
        "apartmentOption": "Apartment",
        "studioOption": "Studio",
        "shopOption": "Shop",
        "marketingTitle": "Contact the Marketing Team",
        "kerollosName": "Eng. Kerollos Noshy",
        "kerollosRole": "Marketing Manager",
        "kirstenName": "Kirsten Atef",
        "kirstenRole": "Marketing",
        "elinName": "Elin Nagah",
        "elinRole": "Marketing",
        "facebookLink": "Facebook",
        "whatsappLink": "Whatsapp",
        "contactTitle": "Contact Us",
        "nameLabel": "Name:",
        "phoneLabel": "Phone Number:",
        "projectLabel": "Project:",
        "hegazOption": "Balkan Compound",
        "interOption": "Inter Project",
        "marinaOption": "Marina Project",
        "hegazOption": "El Hegaz Project",
        "kingTutOption": "King Tut Project",
        "messageLabel": "Message:",
        "submitButton": "Submit",
        "aboutTitle": "Company",
        "aboutContent": "Engineer Shenouda Bashir Real Estate Group is a leading company in the construction and real estate investment field in the Red Sea area. The company was founded with the goal of providing innovative and integrated residential and commercial solutions that meet the needs of our valued customers. We are committed to providing the highest levels of quality in all our projects, focusing on unique design, high-end finishes, and the use of the latest construction technologies.",
        "missionTitle": "Company Mission",
        "missionContent": "We strive to achieve customer satisfaction by offering high-quality real estate projects that contribute to improving the quality of life and enhancing successful investments.",
        "ownerTitle": "About the Owner",
        "ownerName": "Eng. Shenouda Bashir",
        "ownerContent": "Engineer Shenouda Bashir is one of the prominent figures in the construction and real estate field in the Red Sea area. With his extensive experience spanning many years, he is committed to providing exceptional real estate projects that meet the highest global standards.",
        "contactDetailsTitle": "For more details or inquiries, you can contact us via:",
        "footerText": "© 2024 Engineer Shenouda Bashir Real Estate Group. All rights reserved."

    },
    "de": {
        // الترجمات الخاصة بالمشاريع والأقسام
        "projects": "Projekte",
        "about": "Über uns",
        "marketingTeam": "Marketing-Team",
        "contact": "Kontaktieren Sie uns",
        "arabic": "Arabisch",
        "english": "Englisch",
        "german": "Deutsch",
        "russian": "Russisch",
        "french": "Französisch",
        "spanish": "Spanisch",
        
        // الترجمات الخاصة بالأزرار
        "mortgage": "Hypothek",
        "shops": "Läden",
        "installments": "Einheiten in Raten",
        "companyPresentation": "Ingenieur Shenouda Basheer Gruppe",
        "projectTitle": "Inter Star Projekt",
        "projectLocation": "Standort: Hinter dem Al Hayat Krankenhaus - Intercontinental - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "projectDescription": "3 Studios verfügbar\n\n✨Das Studio ist 47 m² groß und enthält ein Zimmer, ein Wohnzimmer und einen Balkon mit Blick auf den Pool.\n\n✨Die Lage ist in der Nähe aller Dienstleistungen:\n1- Al Hayat Krankenhaus\n2- In der Nähe des Strandes 9\n3- Die russische Botschaft\n\n✨Zahlungsmethoden:\n50% Anzahlung, der Rest in Raten über 1 Jahr\n10% Wartungsgebühr bei der Lieferung, gültig auf Lebenszeit",

        "compoundMarminaAlt": "Komplex Marmina",
        "compoundMarminaTitle": "Komplex Marmina",
        "compoundMarminaLocation": "Standort: Neben der Marmina-Kirche - Hinter der Bildungsdirektion - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "compoundMarminaDescription": "🏤Komplex Marmina in Hurghada\nWohnungen und Studios mit Ratenzahlung 🏡\n\n🔸 Wohnungsgrößen:\n📐 85m² - 95m² - 100m² - 105m² - 115m²\n\n🔸 Studio-Größen:\n📐 55m² - 60m² - 65m² - 70m²\n\n🛋️ Intelligente Innenaufteilung: 1, 2 oder 3 Zimmer mit Wohnzimmer, geeignet für alle Bedürfnisse 👨‍👩‍👧‍👦\n\n🔸 Merkmale des Komplexes:\n✨ Alle Wohnungen haben Balkone mit Blick auf den Pool 🌊\n✨ Zwei Aufzüge für einfache Bewegung 🛗\n✨ Swimmingpool 🏊‍♂️\n✨ 24/7-Sicherheit und Bewachung 🛡️\n✨ Überwachungskameras im gesamten Komplex 🎥\n\n🔸 Preise:\n💰 Preis pro Quadratmeter:\nBargeld: 12,000 EGP 💵\nRatenzahlung: 12,500 EGP 💳\n\n💡 Ratenzahlungsplan:\n50% Anzahlung, der Rest über anderthalb Jahre 📆",
        "kingTutAlt": "Projekt König Tut",
        "kingTutTitle": "König Tut Gebäude",
        "kingTutLocation": "Standort: Tawfiq Bezirk - Neben dem König Tut Hotel - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "kingTutDescription": "✨Noch 3 Gewerbeflächen verfügbar\n✨Größen: 20m - 25m - 58m\n✨Eingetragenes grünes Vertrag\n✨Flexible Zahlungsoptionen und sofortige Lieferung",
        "hegazAlt": "Hegaz Gebäude",
        "hegazTitle": "Hegaz Gebäude",
        "hegazLocation": "Standort: Vor der Al-Mohandes Ersatzteilfirma - Hegaz Straße - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "hegazDescription": "🏛️Wohnungen zum Verkauf in Hegaz 🏢\n📍 In der Nähe der Gouverneursgebäude und des neuen Marktes von Hurghada\n📍 Vor der Al-Mohandes Ersatzteilfirma auf der Hegaz Straße\n🔑 Immobilienmerkmale:\n🔹 Das Grundstück ist mit einem grünen Vertrag registriert und umfasst einen Anteil am Land 🌍\n🔹 Das Gebäude ist neu und verfügt über einen Aufzug 🛗\n📏 Verfügbare Wohnungsgrößen:\n110 - 115 - 120 - 125 Quadratmeter 🛏️📐\n✨ Perfekte Aufteilung für Familien: 3 Schlafzimmer 👨‍👩‍👧‍👦\n💰 Preise:\nPreis pro Quadratmeter (Rohbau): 13,000 EGP bar 💵\nPreis pro Quadratmeter (Rohbau): 13,500 EGP in Raten 💳\n💡 Ratenplan: 50% Anzahlung, der Rest in flexiblen Zahlungen über 6 Monate 📆",
        "portBuildingAlt": "Hafen Gebäude",
        "portBuildingTitle": "Hafen Gebäude",
        "portBuildingLocation": "Standort: In der Nähe des Touristengebiets Hurghada Marina - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "portBuildingDescription": "🏛️Hafenprojekt im Herzen von Hurghada.\n🌟In der Nähe der Touristenmarina und aller Dienstleistungen\n🌟 Wohnimmobilien verfügbar zum Verkauf:\n🔸 Wohnung 120m (drei Zimmer)\n🔸 Studio 55m (Hotelzimmer)\n🔸 Studio 55m (Schlafzimmer)\n💵Flexible Zahlungsoptionen und Rabatte bei Barzahlung"
        ,"jewelBuildingAlt": "Die Juwel",
        "jewelBuildingTitle": "Juwel Gebäude",
        "jewelBuildingLocation": "Standort: Hauptbezirk - Neben der Mutter Dolagy Kirche - Hurghada",
        "projectDescriptionButton": "Beschreibung",
        "sendButton": "Senden",
        "jewelBuildingDescription": "Ein Geschäft von 80m² ist verfügbar (Rohbau)"
        ,"projectDescriptionButton": "Beschreibung",
        "embassyBuildingAlt": "Botschaft",
        "embassyBuildingTitle": "Al-Hodaba Gebäude",
        "embassyBuildingLocation": "Standort: Al-Hodaba - Neben der deutschen Botschaft - Hurghada",
        "embassyBuildingDescription": "Alle Einheiten sind verkauft",
        "maktabBuildingAlt": "Botschaft",
        "maktabBuildingTitle": "Al-Hodaba Gebäude",
        "maktabBuildingLocation": "Standort: Metro Straße, Sheraton - Hurghada",
        "maktabBuildingDescription": "Alle Einheiten sind verkauft",
        "ahiaBuildingAlt": "Botschaft",
        "ahiaBuildingTitle": "Juwelen Gebäude",
        "ahiaBuildingLocation": "Standort: Hauptbezirk - Hurghada",
        "ahiaBuildingDescription": "Alle Einheiten sind verkauft",
        "wafaBuildingAlt": "Botschaft",
        "wafaBuildingTitle": "Al-Wafa Gebäude",
        "wafaBuildingLocation": "Standort: Neben dem Radiozaun - Hurghada",
        "wafaBuildingDescription": "Alle Einheiten sind verkauft",
        "propertyModalTitle": "Worüber fragen Sie?",
        "closeButton": "×",
        "apartmentOption": "Wohnung",
        "studioOption": "Studio",
        "shopOption": "Geschäft",
        "marketingTitle": "Kontaktieren Sie das Marketing-Team",
        "kerollosName": "Ing. Kerollos Noshy",
        "kerollosRole": "Marketing Manager",
        "kirstenName": "Kirsten Atef",
        "kirstenRole": "Marketing",
        "elinName": "Elin Nagah",
        "elinRole": "Marketing",
        "facebookLink": "Facebook",
        "whatsappLink": "Whatsapp",
        "contactTitle": "Kontaktiere uns",
        "nameLabel": "Name:",
        "phoneLabel": "Telefonnummer:",
        "projectLabel": "Projekt:",
        "hegazOption": "Balkan Komplex",
        "interOption": "Inter Projekt",
        "marinaOption": "Marina Projekt",
        "hegazOption": "El Hegaz Projekt",
        "kingTutOption": "King Tut Projekt",
        "messageLabel": "Nachricht:",
        "submitButton": "Absenden",
        "aboutTitle": "Unternehmen",
        "aboutContent": "Die Ingenieur Shenouda Bashir Real Estate Group ist ein führendes Unternehmen im Bereich Bauwesen und Immobilieninvestitionen im Rotmeergebiet. Das Unternehmen wurde mit dem Ziel gegründet, innovative und integrierte Wohn- und Geschäftslösungen anzubieten, die den Bedürfnissen unserer geschätzten Kunden gerecht werden. Wir verpflichten uns, in allen unseren Projekten die höchsten Qualitätsstandards zu bieten, mit Fokus auf einzigartiges Design, hochwertige Ausstattungen und den Einsatz der neuesten Bautechnologien.",
        "missionTitle": "Unternehmensmission",
        "missionContent": "Wir streben danach, die Kundenzufriedenheit zu erreichen, indem wir hochwertige Immobilienprojekte anbieten, die zur Verbesserung der Lebensqualität beitragen und erfolgreiche Investitionen fördern.",
        "ownerTitle": "Über den Eigentümer",
        "ownerName": "Ing. Shenouda Bashir",
        "ownerContent": "Ingenieur Shenouda Bashir ist eine der herausragenden Persönlichkeiten im Bereich Bauwesen und Immobilien im Rotmeergebiet. Mit seiner umfangreichen Erfahrung, die sich über viele Jahre erstreckt, setzt er sich dafür ein, außergewöhnliche Immobilienprojekte anzubieten, die den höchsten globalen Standards entsprechen.",
        "contactDetailsTitle": "Für weitere Details oder Anfragen können Sie uns über folgende Kanäle kontaktieren:",
        "footerText": "© 2024 Ingenieur Shenouda Bashir Real Estate Group. Alle Rechte vorbehalten."


    },
    "ru": {
        // الترجمات الخاصة بالمشاريع والأقسام
        "projects": "Проекты",
        "about": "О нас",
        "marketingTeam": "Маркетинговая команда",
        "contact": "Свяжитесь с нами",
        "arabic": "Арабский",
        "english": "Английский",
        "german": "Немецкий",
        "russian": "Русский",
        "french": "Французский",
        "spanish": "Испанский",
        
        // الترجمات الخاصة بالأزرار
        "mortgage": "Ипотека",
        "shops": "Магазины",
        "installments": "Единицы в рассрочку",
        "companyPresentation": "Группа инженера Шенуды Башира",
        "projectTitle": "Проект Интер Стар",
        "projectLocation": "Местоположение: За больницей Аль Хая - Интерконтиненталь - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "projectDescription": "3 студии в наличии\n\n✨Студия площадью 47 м², с одной комнатой, гостиной и балконом с видом на бассейн.\n\n✨Местоположение рядом со всеми услугами:\n1- Больница Аль Хая\n2- Рядом с пляжем 9\n3- Российское посольство\n\n✨Способы оплаты:\n50% предоплата, остальное в рассрочку на 1 год\n10% депозит на обслуживание при получении, бессрочно",
        "compoundMarminaAlt": "Комплекс Мармина",
        "compoundMarminaTitle": "Комплекс Мармина",
        "compoundMarminaLocation": "Местоположение: Рядом с церковью Мармина - За Дирекцией образования - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "compoundMarminaDescription": "🏤Комплекс Мармина в Хургаде\nКвартиры и студии в рассрочку 🏡\n\n🔸 Размеры квартир:\n📐 85м² - 95м² - 100м² - 105м² - 115м²\n\n🔸 Размеры студий:\n📐 55м² - 60м² - 65м² - 70м²\n\n🛋️ Умное внутреннее оформление: 1, 2 или 3 комнаты с гостиной, подходит для всех потребностей 👨‍👩‍👧‍👦\n\n🔸 Особенности комплекса:\n✨ Все квартиры имеют балконы с видом на бассейн 🌊\n✨ Два лифта для удобного передвижения 🛗\n✨ Бассейн 🏊‍♂️\n✨ Круглосуточная охрана 🛡️\n✨ Камеры наблюдения по всему комплексу 🎥\n\n🔸 Цены:\n💰 Цена за квадратный метр:\nНаличные: 12,000 EGP 💵\nРассрочка: 12,500 EGP 💳\n\n💡 План рассрочки:\n50% предоплата, остальное в течение полутора лет 📆",
        "kingTutAlt": "Проект Король Тут",
        "kingTutTitle": "Здание Король Тут",
        "kingTutLocation": "Местоположение: Район Тафик - Рядом с Отелем Король Тут - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "kingTutDescription": "✨Осталось 3 коммерческих магазина\n✨Размеры: 20м - 25м - 58м\n✨Зарегистрированный зелёный контракт\n✨Гибкие варианты оплаты и немедленная доставка",
        "hegazAlt": "Здание Хегаз",
        "hegazTitle": "Здание Хегаз",
        "hegazLocation": "Местоположение: Перед компанией Al-Mohandes Spare Parts - Дорога Хегаз - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "hegazDescription": "🏛️Квартиры на продажу в Хегаз 🏢\n📍 Рядом с губернаторскими зданиями и новым рынком Хургады\n📍 Перед компанией Al-Mohandes Spare Parts на дороге Хегаз\n🔑 Особенности недвижимости:\n🔹 Недвижимость зарегистрирована с зеленым контрактом и включает долю земли 🌍\n🔹 Здание новое и оснащено лифтом 🛗\n📏 Доступные размеры квартир:\n110 - 115 - 120 - 125 квадратных метров 🛏️📐\n✨ Идеальная планировка для семей: 3 спальни 👨‍👩‍👧‍👦\n💰 Цены:\nЦена за квадратный метр (черновая отделка): 13,000 EGP наличными 💵\nЦена за квадратный метр (черновая отделка): 13,500 EGP в рассрочку 💳\n💡 План рассрочки: 50% первоначального взноса, остальное в рассрочку на 6 месяцев 📆"
        ,"portBuildingAlt": "Здание Порт",
        "portBuildingTitle": "Здание Порт",
        "portBuildingLocation": "Местоположение: Рядом с туристической зоной Хургада Марина - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "portBuildingDescription": "🏛️Проект Порт в самом сердце Хургады.\n🌟Близко к туристической марине и всем услугам\n🌟 Жилые единицы доступны для продажи:\n🔸 Квартира 120м (три комнаты)\n🔸 Студия 55м (гостиничный номер)\n🔸 Студия 55м (спальня)\n💵Гибкие варианты оплаты и скидки при оплате наличными"
        ,"jewelBuildingAlt": "Жемчужина",
        "jewelBuildingTitle": "Здание Жемчужина",
        "jewelBuildingLocation": "Местоположение: Главный район - Рядом с церковью Матери Долаги - Хургада",
        "projectDescriptionButton": "Описание",
        "sendButton": "Отправить",
        "jewelBuildingDescription": "Доступен коммерческий магазин площадью 80м² (состояние черновой отделки)"
        ,"projectDescriptionButton": "Описание",
        "embassyBuildingAlt": "Посольство",
        "embassyBuildingTitle": "Здание Аль-Ходаба",
        "embassyBuildingLocation": "Местоположение: Аль-Ходаба - Рядом с немецким посольством - Хургада",
        "embassyBuildingDescription": "Все квартиры проданы",
        "maktabBuildingAlt": "Посольство",
        "maktabBuildingTitle": "Здание Аль-Ходаба",
        "maktabBuildingLocation": "Местоположение: Улица метро, Шератон - Хургада",
        "maktabBuildingDescription": "Все квартиры проданы",
        "ahiaBuildingAlt": "Посольство",
        "ahiaBuildingTitle": "Здание Жемчужины",
        "ahiaBuildingLocation": "Местоположение: Главный район - Хургада",
        "ahiaBuildingDescription": "Все квартиры проданы",
        "wafaBuildingAlt": "Посольство",
        "wafaBuildingTitle": "Здание Аль-Вафа",
        "wafaBuildingLocation": "Местоположение: Рядом с радиозабором - Хургада",
        "wafaBuildingDescription": "Все квартиры проданы",
        "propertyModalTitle": "О чем вы спрашиваете?",
        "closeButton": "×",
        "apartmentOption": "Квартира",
        "studioOption": "Студия",
        "shopOption": "Магазин",
        "marketingTitle": "Связаться с командой маркетинга",
        "kerollosName": "Инж. Кероллос Насри",
        "kerollosRole": "Менеджер по маркетингу",
        "kirstenName": "Кирстен Аттеф",
        "kirstenRole": "Маркетинг",
        "elinName": "Элин Нагах",
        "elinRole": "Маркетинг",
        "facebookLink": "Facebook",
        "whatsappLink": "Whatsapp",
        "contactTitle": "Свяжитесь с нами",
        "nameLabel": "Имя:",
        "phoneLabel": "Номер телефона:",
        "projectLabel": "Проект:",
        "hegazOption": "Комплекс Балкан",
        "interOption": "Проект Интер",
        "marinaOption": "Проект Марины",
        "hegazOption": "Проект Эль-Хегаз",
        "kingTutOption": "Проект Кинг Тут",
        "messageLabel": "Сообщение:",
        "submitButton": "Отправить",
        "aboutTitle": "Компания",
        "aboutContent": "Группа недвижимости инженера Шенуды Башира - ведущая компания в области строительства и инвестиции в недвижимость в районе Красного моря. Компания была основана с целью предоставления инновационных и интегрированных жилых и коммерческих решений, которые удовлетворяют потребности наших уважаемых клиентов. Мы стремимся предоставлять проекты самого высокого качества, с акцентом на уникальный дизайн, высококачественные отделочные материалы и использование новейших технологий строительства.",
        "missionTitle": "Миссия компании",
        "missionContent": "Мы стремимся к удовлетворению потребностей наших клиентов, предлагая высококачественные проекты недвижимости, которые способствуют улучшению качества жизни и поддержке успешных инвестиций.",
        "ownerTitle": "О владельце",
        "ownerName": "Инж. Шенуда Башир",
        "ownerContent": "Инженер Шенуда Башир - одна из видных фигур в области строительства и недвижимости в районе Красного моря. С его обширным опытом, который охватывает многие годы, он стремится предоставлять исключительные проекты недвижимости, соответствующие самым высоким мировым стандартам.",
        "contactDetailsTitle": "Для получения дополнительной информации или для консультаций вы можете связаться с нами по следующим каналам:",
        "footerText": "© 2024 Группа недвижимости инженера Шенуды Башира. Все права защищены."


    },
    "fr": {
        // الترجمات الخاصة بالمشاريع والأقسام
        "projects": "Projets",
        "about": "À propos",
        "marketingTeam": "Équipe marketing",
        "contact": "Contactez-nous",
        "arabic": "Arabe",
        "english": "Anglais",
        "german": "Allemand",
        "russian": "Russe",
        "french": "Français",
        "spanish": "Espagnol",
        
        // الترجمات الخاصة بالأزرار
        "mortgage": "Prêt hypothécaire",
        "shops": "Magasins",
        "installments": "Unités en mensualités",
        "companyPresentation": "Le groupe de l'ingénieur Shenouda Basheer",
        "projectTitle": "Projet Inter Star",
        "projectLocation": "Emplacement: Derrière l'hôpital Al Hayat - Intercontinental - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "projectDescription": "3 studios disponibles\n\n✨Le studio mesure 47 m², avec une chambre, un salon et un balcon donnant sur la piscine.\n\n✨L'emplacement est proche de tous les services:\n1- Hôpital Al Hayat\n2- Près de la plage 9\n3- L'ambassade russe\n\n✨Méthodes de paiement:\n50% d'acompte, le reste en plusieurs fois sur 1 an\nDépôt de maintenance de 10% à la livraison, valable à vie",
        "compoundMarminaAlt": "Complexe Marmina",
        "compoundMarminaTitle": "Complexe Marmina",
        "compoundMarminaLocation": "Emplacement : À côté de l'église Marmina - Derrière la Direction de l'Éducation - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "compoundMarminaDescription": "🏤Complexe Marmina à Hurghada\nAppartements et studios disponibles avec paiements échelonnés 🏡\n\n🔸 Tailles des appartements :\n📐 85m² - 95m² - 100m² - 105m² - 115m²\n\n🔸 Tailles des studios :\n📐 55m² - 60m² - 65m² - 70m²\n\n🛋️ Disposition intérieure intelligente : 1, 2 ou 3 chambres avec un salon, adaptée à tous les besoins 👨‍👩‍👧‍👦\n\n🔸 Caractéristiques du complexe :\n✨ Tous les appartements ont des balcons avec vue sur la piscine 🌊\n✨ Deux ascenseurs pour un déplacement facile 🛗\n✨ Piscine 🏊‍♂️\n✨ Sécurité 24/7 🛡️\n✨ Caméras de surveillance réparties dans tout le complexe 🎥\n\n🔸 Prix :\n💰 Prix au mètre carré :\nComptant : 12,000 EGP 💵\nPaiements échelonnés : 12,500 EGP 💳\n\n💡 Plan de paiements :\n50% d'acompte, le reste sur un an et demi 📆",
        "kingTutAlt": "Projet Roi Toutankhamon",
        "kingTutTitle": "Bâtiment Roi Toutankhamon",
        "kingTutLocation": "Emplacement : Quartier Tawfiq - À côté de l'hôtel Roi Toutankhamon - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "kingTutDescription": "✨3 magasins commerciaux restants\n✨Dimensions : 20m - 25m - 58m\n✨Contrat vert enregistré\n✨Options de paiement flexibles et livraison immédiate",
        "hegazAlt": "Immeuble Al-Hegaz",
        "hegazTitle": "Immeuble Al-Hegaz",
        "hegazLocation": "Emplacement : En face de la société Al-Mohandes pour pièces détachées - Route Al-Hegaz - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "hegazDescription": "🏛️Appartements à vendre à Al-Hegaz 🏢\n📍 Près des immeubles du gouvernorat et du nouveau marché d'Hurghada\n📍 En face de la société Al-Mohandes pour pièces détachées sur la route Al-Hegaz\n🔑 Caractéristiques de la propriété :\n🔹 Propriété enregistrée avec un contrat vert et part de terrain incluse 🌍\n🔹 Immeuble neuf avec ascenseur 🛗\n📏 Tailles d'appartements disponibles :\n110 - 115 - 120 - 125 mètres carrés 🛏️📐\n✨ Aménagement idéal pour les familles : 3 chambres 👨‍👩‍👧‍👦\n💰 Prix :\nPrix au mètre carré (structure) : 13 000 EGP comptant 💵\nPrix au mètre carré (structure) : 13 500 EGP en plusieurs fois 💳\n💡 Plan de paiement : 50% d'acompte, le reste en paiements flexibles sur 6 mois 📆"
        ,"portBuildingAlt": "Immeuble Port",
        "portBuildingTitle": "Immeuble Port",
        "portBuildingLocation": "Emplacement : Près de la Marina touristique d'Hurghada - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "portBuildingDescription": "🏛️Projet Port au cœur d'Hurghada.\n🌟Proche de la marina touristique et de tous les services\n🌟 Unités résidentielles disponibles à la vente :\n🔸 Appartement 120m (trois chambres)\n🔸 Studio 55m (chambre d'hôtel)\n🔸 Studio 55m (chambre à coucher)\n💵Options de paiement flexibles et réductions pour paiement comptant"
        ,"jewelBuildingAlt": "Le Joyau",
        "jewelBuildingTitle": "Immeuble Le Joyau",
        "jewelBuildingLocation": "Emplacement : Quartier Principal - À côté de l'église Mère Dolagy - Hurghada",
        "projectDescriptionButton": "Description",
        "sendButton": "Envoyer",
        "jewelBuildingDescription": "Un local commercial de 80m² est disponible (en état brut)"
        ,"projectDescriptionButton": "Description",
        "embassyBuildingAlt": "Ambassade",
        "embassyBuildingTitle": "Immeuble Al-Hodaba",
        "embassyBuildingLocation": "Emplacement : Al-Hodaba - À côté de l'ambassade allemande - Hurghada",
        "embassyBuildingDescription": "Toutes les unités sont vendues",
        "maktabBuildingAlt": "Ambassade",
        "maktabBuildingTitle": "Immeuble Al-Hodaba",
        "maktabBuildingLocation": "Emplacement : Rue du métro, Sheraton - Hurghada",
        "maktabBuildingDescription": "Toutes les unités sont vendues",
        "ahiaBuildingAlt": "Ambassade",
        "ahiaBuildingTitle": "Immeuble Jewel",
        "ahiaBuildingLocation": "Emplacement : Quartier principal - Hurghada",
        "ahiaBuildingDescription": "Toutes les unités sont vendues",
        "wafaBuildingAlt": "Ambassade",
        "wafaBuildingTitle": "Immeuble Al-Wafa",
        "wafaBuildingLocation": "Emplacement : À côté de la clôture de la radio - Hurghada",
        "wafaBuildingDescription": "Toutes les unités sont vendues",
        "propertyModalTitle": "De quoi demandez-vous?",
        "closeButton": "×",
        "apartmentOption": "Appartement",
        "studioOption": "Studio",
        "shopOption": "Magasin",
        "marketingTitle": "Contacter l'équipe marketing",
        "kerollosName": "Ing. Kerollos Noshy",
        "kerollosRole": "Responsable Marketing",
        "kirstenName": "Kirsten Atef",
        "kirstenRole": "Marketing",
        "elinName": "Elin Nagah",
        "elinRole": "Marketing",
        "facebookLink": "Facebook",
        "whatsappLink": "Whatsapp",
        "contactTitle": "Contactez-nous",
        "nameLabel": "Nom:",
        "phoneLabel": "Numéro de téléphone:",
        "projectLabel": "Projet:",
        "hegazOption": "Complexe Balkan",
        "interOption": "Projet Inter",
        "marinaOption": "Projet Marina",
        "hegazOption": "Projet El Hegaz",
        "kingTutOption": "Projet King Tut",
        "messageLabel": "Message:",
        "submitButton": "Envoyer",
        "aboutTitle": "Entreprise",
        "aboutContent": "Le groupe immobilier Shenouda Bashir Engineering est une entreprise leader dans le domaine de la construction et des investissements immobiliers dans la région de la mer Rouge. L'entreprise a été fondée dans le but de fournir des solutions résidentielles et commerciales innovantes et intégrées qui répondent aux besoins de nos précieux clients. Nous nous engageons à fournir les plus hauts niveaux de qualité dans tous nos projets, en mettant l'accent sur le design unique, les finitions de haute qualité et l'utilisation des dernières technologies de construction.",
        "missionTitle": "Mission de l'entreprise",
        "missionContent": "Nous nous efforçons de satisfaire nos clients en proposant des projets immobiliers de haute qualité qui contribuent à améliorer la qualité de vie et à favoriser des investissements réussis.",
        "ownerTitle": "À propos du propriétaire",
        "ownerName": "Ing. Shenouda Bashir",
        "ownerContent": "L'ingénieur Shenouda Bashir est l'une des personnalités les plus importantes dans le domaine de la construction et de l'immobilier dans la région de la mer Rouge. Fort de son expérience étendue s'étalant sur de nombreuses années, il s'engage à fournir des projets immobiliers exceptionnels répondant aux normes mondiales les plus élevées.",
        "contactDetailsTitle": "Pour plus de détails ou des demandes de renseignements, vous pouvez nous contacter via :",
        "footerText": "© 2024 Groupe immobilier Shenouda Bashir. Tous droits réservés."


    },
    "es": {
        // الترجمات الخاصة بالمشاريع والأقسام
        "projects": "Proyectos",
        "about": "Acerca de nosotros",
        "marketingTeam": "Equipo de marketing",
        "contact": "Contáctenos",
        "arabic": "Árabe",
        "english": "Inglés",
        "german": "Alemán",
        "russian": "Ruso",
        "french": "Francés",
        "spanish": "Español",
        
        // الترجمات الخاصة بالأزرار
        "mortgage": "Hipoteca",
        "shops": "Tiendas",
        "installments": "Unidades a plazos",
        "companyPresentation": "El grupo del ingeniero Shenouda Basheer",
        "projectTitle": "Proyecto Inter Star",
        "projectLocation": "Ubicación: Detrás del hospital Al Hayat - Intercontinental - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "projectDescription": "3 estudios disponibles\n\n✨El estudio tiene 47 m², con una habitación, una sala de estar y un balcón con vista a la piscina.\n\n✨La ubicación está cerca de todos los servicios:\n1- Hospital Al Hayat\n2- Cerca de la playa 9\n3- La embajada rusa\n\n✨Métodos de pago:\n50% de pago inicial, el resto en cuotas durante 1 año\nDepósito de mantenimiento del 10% a la entrega, válido de por vida",
        "compoundMarminaAlt": "Complejo Marmina",
        "compoundMarminaTitle": "Complejo Marmina",
        "compoundMarminaLocation": "Ubicación: Junto a la Iglesia de Marmina - Detrás de la Dirección de Educación - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "compoundMarminaDescription": "🏤Complejo Marmina en Hurghada\nApartamentos y estudios disponibles con pagos a plazos 🏡\n\n🔸 Tamaños de los apartamentos:\n📐 85m² - 95m² - 100m² - 105m² - 115m²\n\n🔸 Tamaños de los estudios:\n📐 55m² - 60m² - 65m² - 70m²\n\n🛋️ Disposición interior inteligente: 1, 2 o 3 habitaciones con sala de estar, adecuado para todas las necesidades 👨‍👩‍👧‍👦\n\n🔸 Características del complejo:\n✨ Todos los apartamentos tienen balcones con vista a la piscina 🌊\n✨ Dos ascensores para un movimiento fácil 🛗\n✨ Piscina 🏊‍♂️\n✨ Seguridad 24/7 🛡️\n✨ Cámaras de vigilancia distribuidas por todo el complejo 🎥\n\n🔸 Precios:\n💰 Precio por metro cuadrado:\nEfectivo: 12,000 EGP 💵\nPagos a plazos: 12,500 EGP 💳\n\n💡 Plan de pagos:\n50% de pago inicial, el resto en un año y medio 📆",
        "kingTutAlt": "Proyecto Rey Tut",
        "kingTutTitle": "Edificio Rey Tut",
        "kingTutLocation": "Ubicación: Distrito Tawfiq - Junto al Hotel Rey Tut - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "kingTutDescription": "✨3 tiendas comerciales restantes\n✨Tamaños: 20m - 25m - 58m\n✨Contrato verde registrado\n✨Opciones de pago flexibles y entrega inmediata",
        "hegazAlt": "Edificio Al-Hegaz",
        "hegazTitle": "Edificio Al-Hegaz",
        "hegazLocation": "Ubicación: Frente a la compañía Al-Mohandes para repuestos - Carretera Al-Hegaz - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "hegazDescription": "🏛️Apartamentos en venta en Al-Hegaz 🏢\n📍 Cerca de los edificios del gobernador y el nuevo mercado de Hurghada\n📍 Frente a la compañía Al-Mohandes para repuestos en la carretera Al-Hegaz\n🔑 Características de la propiedad:\n🔹 Propiedad registrada con contrato verde y participación en el terreno incluida 🌍\n🔹 Edificio nuevo con ascensor 🛗\n📏 Tamaños de apartamentos disponibles:\n110 - 115 - 120 - 125 metros cuadrados 🛏️📐\n✨ Distribución perfecta para familias: 3 dormitorios 👨‍👩‍👧‍👦\n💰 Precios:\nPrecio por metro cuadrado (obra gruesa): 13,000 EGP en efectivo 💵\nPrecio por metro cuadrado (obra gruesa): 13,500 EGP en cuotas 💳\n💡 Plan de pago: 50% de pago inicial, el resto en pagos flexibles en 6 meses 📆"
        ,"portBuildingAlt": "Edificio del Puerto",
        "portBuildingTitle": "Edificio del Puerto",
        "portBuildingLocation": "Ubicación: Cerca de la zona turística de la Marina de Hurghada - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "portBuildingDescription": "🏛️Proyecto del Puerto en el corazón de Hurghada.\n🌟Cerca de la marina turística y de todos los servicios\n🌟 Unidades residenciales disponibles para la venta:\n🔸 Apartamento 120m (tres habitaciones)\n🔸 Estudio 55m (habitación de hotel)\n🔸 Estudio 55m (habitación)\n💵Opciones de pago flexibles y descuentos en efectivo"
        , "jewelBuildingAlt": "La Joya",
        "jewelBuildingTitle": "Edificio La Joya",
        "jewelBuildingLocation": "Ubicación: Distrito Principal - Junto a la Iglesia Madre Dolagy - Hurghada",
        "projectDescriptionButton": "Descripción",
        "sendButton": "Enviar",
        "jewelBuildingDescription": "Disponible un local comercial de 80m² (en estado de obra)"
        ,"projectDescriptionButton": "Descripción",
        "embassyBuildingAlt": "Embajada",
        "embassyBuildingTitle": "Edificio Al-Hodaba",
        "embassyBuildingLocation": "Ubicación: Al-Hodaba - Junto a la embajada alemana - Hurghada",
        "embassyBuildingDescription": "Todas las unidades están vendidas",
        "maktabBuildingAlt": "Embajada",
        "maktabBuildingTitle": "Edificio Al-Hodaba",
        "maktabBuildingLocation": "Ubicación: Calle del metro, Sheraton - Hurghada",
        "maktabBuildingDescription": "Todas las unidades están vendidas",
        "ahiaBuildingAlt": "Embajada",
        "ahiaBuildingTitle": "Edificio Jewel",
        "ahiaBuildingLocation": "Ubicación: Barrio principal - Hurghada",
        "ahiaBuildingDescription": "Todas las unidades están vendidas",
        "wafaBuildingAlt": "Embajada",
        "wafaBuildingTitle": "Edificio Al-Wafa",
        "wafaBuildingLocation": "Ubicación: Junto a la cerca de la radio - Hurghada",
        "wafaBuildingDescription": "Todas las unidades están vendidas",
        "propertyModalTitle": "¿Sobre qué estás preguntando?",
        "closeButton": "×",
        "apartmentOption": "Apartamento",
        "studioOption": "Estudio",
        "shopOption": "Tienda",
        "marketingTitle": "Contacta con el equipo de marketing",
        "kerollosName": "Ing. Kerollos Noshy",
        "kerollosRole": "Gerente de marketing",
        "kirstenName": "Kirsten Atef",
        "kirstenRole": "Marketing",
        "elinName": "Elin Nagah",
        "elinRole": "Marketing",
        "facebookLink": "Facebook",
        "whatsappLink": "Whatsapp",
        "contactTitle": "Contáctanos",
        "nameLabel": "Nombre:",
        "phoneLabel": "Número de teléfono:",
        "projectLabel": "Proyecto:",
        "hegazOption": "Complejo Balkan",
        "interOption": "Proyecto Inter",
        "marinaOption": "Proyecto Marina",
        "hegazOption": "Proyecto El Hegaz",
        "kingTutOption": "Proyecto King Tut",
        "messageLabel": "Mensaje:",
        "submitButton": "Enviar",
        "aboutTitle": "Compañía",
        "aboutContent": "El grupo inmobiliario Shenouda Bashir Engineering es una empresa líder en el campo de la construcción e inversión inmobiliaria en la zona del Mar Rojo. La empresa fue fundada con el objetivo de ofrecer soluciones residenciales y comerciales innovadoras e integradas que satisfagan las necesidades de nuestros valiosos clientes. Nos comprometemos a ofrecer los más altos niveles de calidad en todos nuestros proyectos, con un enfoque en el diseño único, acabados de alta gama y el uso de las últimas tecnologías de construcción.",
        "missionTitle": "Misión de la empresa",
        "missionContent": "Nos esforzamos por lograr la satisfacción de nuestros clientes ofreciendo proyectos inmobiliarios de alta calidad que contribuyen a mejorar la calidad de vida y fomentar inversiones exitosas.",
        "ownerTitle": "Acerca del propietario",
        "ownerName": "Ing. Shenouda Bashir",
        "ownerContent": "El ingeniero Shenouda Bashir es una de las figuras destacadas en el campo de la construcción e inmobiliaria en la zona del Mar Rojo. Con su vasta experiencia que abarca muchos años, se compromete a ofrecer proyectos inmobiliarios excepcionales que cumplen con los más altos estándares internacionales.",
        "contactDetailsTitle": "Para más detalles o consultas, puede contactarnos a través de:",
        "footerText": "© 2024 Grupo inmobiliario Shenouda Bashir. Todos los derechos reservados."

    }
};




// إضافة حدث عند تغيير اللغة
document.getElementById("languageSelector").addEventListener("change", function () {
    const selectedLanguage = this.value; // اللغة المختارة
    const elementsToTranslate = document.querySelectorAll("[data-translate-key]");

    // تحديث النصوص في الصفحة
    elementsToTranslate.forEach(element => {
        const key = element.getAttribute("data-translate-key");
        if (translations[selectedLanguage] && translations[selectedLanguage][key]) {
            element.textContent = translations[selectedLanguage][key];
        }
    });
});

function changeLanguage(language) {
    const elements = document.querySelectorAll("[data-translate-key]");
    elements.forEach((element) => {
        const key = element.getAttribute("data-translate-key");
        if (translations[language] && translations[language][key]) {
            element.textContent = translations[language][key];
        }
    });
}
